#!/bin/sh

if [ -f /var/lib/sailfish-device-encryption/encrypt-home ]; then
    # Stop target units that must be started after encryption
    systemctl stop graphical.target
    systemctl stop multi-user.target
    # Mask home.mount so that it won't be started until encryption finishes
    systemctl mask --runtime home.mount
    systemctl daemon-reload
    # Run home encryption, will also unmask home.mount
    /usr/lib/startup/qa-encrypt-device
    # Modify pam system-auth to get QA ssh access in acting dead
    sed -i '/pam_systemd.so/c\-session     optional      pam_systemd.so timeout=10' /etc/pam.d/system-auth
fi
