#!/bin/sh

if [ -f /var/lib/sailfish-device-encryption/encrypt-home ]; then
    # Mask home.mount so that it won't be started until encryption finishes
    systemctl mask --runtime home.mount
    systemctl daemon-reload
    # Run home encryption, will also unmask home.mount
    /usr/lib/startup/qa-encrypt-device
fi
